### ISSUE TITLE
On the first time opening Log Dialog, the bot answers random phrases

### ISSUE THREAD

**Issue by BelvedereHenrique** [Microsoft/ConversationLearner-Samples#188]
Hi,

Whenever you open, for the first time, the Log Dialog window, after the first message, the bot sends random messages based on trained entities.
![image](https://user-images.githubusercontent.com/24565006/40124376-d03f3de4-58fe-11e8-9f53-9c1037ee5c29.png)

**Comment by BelvedereHenrique** [comment]
If you click on "Done Testing" then try again, the issue does not occur again.
![image](https://user-images.githubusercontent.com/24565006/40124469-06185d74-58ff-11e8-9d0c-9380d2e961e8.png)

**Comment by jasondwilliams** [comment]
Hi @BelvedereHenrique - thanks for reporting.  This can occur if there are multiple browser windows open (possibly among other cases).  We have a fix coming; we'll update this issue when that's merged into master.  Thanks!

**Comment by LarsLiden** [comment]
Fixed in #192 (dev branch)
