### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by technoprax** [Microsoft/ConversationLearner-Samples#190]
> E:\git\my-bot-01\lib\app.js:35
> const { bfAppId, bfAppPassword, clAppId } = config_1.default, clOptions = __rest(config_1.default
>       ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3

**Comment by BelvedereHenrique** [comment]
Did you try npm install and npm run build?

**Comment by technoprax** [comment]
Yes, still same error. I am following the steps mentioned [Here](https://github.com/Microsoft/ConversationLearner-Samples#quick-start)

**Comment by mattmazzola** [comment]
I'm guessing his version of node doesn't support destructuring which I think was added in Node 6.x

**Comment by LarsLiden** [comment]
@technoprax  - going to mark this issue as closed as you haven't responded.  Please feel free to re-open if you are still having any difficulty
