### ISSUE TITLE
DELETE_TRAIN_DIALOG_REJECTED error when "Action" is created without "Wait for Response?"

### ISSUE THREAD

**Issue by lucascologni** [Microsoft/ConversationLearner-Samples#193]
An error called "DELETE_TRAIN_DIALOG_REJECTED Failed" is triggered when an "Action" is created with the "Wait for Response?" field not checked.

![test](https://user-images.githubusercontent.com/12294328/40191597-5f6931c6-59d8-11e8-893b-c267a8dd7474.PNG)
![test2](https://user-images.githubusercontent.com/12294328/40191608-6673e196-59d8-11e8-846f-94f6d69042a3.PNG)

Could you check please? 

Thank you guys!

@BelvedereHenrique, @Cley-94, @flaviol-souza @RafaelMD

**Comment by LarsLiden** [comment]
@lucascologni - I haven't been able to repro this one.  Does it happen every time for you?  Any other context about what you were doing before this happened?

**Comment by lucascologni** [comment]
@LarsLiden, I was verifying together with some guys for my team the same situation.

But maybe we doing something wrong too... I don't know. Can you try to repro this one?

What we did to test was simple... First we created an action with the response "Hello World!", then we unchecked the option "Wait For Response?".

So far so good, so we created a new train dialog with the word "Hello", then we selected the response "Hello World!", this error is triggered after clicking on the button "Done Teaching".

Thanks! :)

**Comment by LarsLiden** [comment]
Thanks for the additional detail - I'm able to repro now.   I see the issue, the train dialog is getting rejected because currently we require that all train dialogs end with a terminal action.  Let me think about this a bit more to see if we can relax this requirement.  (@msft-shahins )

**Comment by lucascologni** [comment]
Sure! Thanks @LarsLiden :)

**Comment by BelvedereHenrique** [comment]
@lucascologni, have you tried a new git clone? As we're dipping into the code, we may have changed something

**Comment by BelvedereHenrique** [comment]
Makes sense.

**Comment by lucascologni** [comment]
When you are creating the first action, what do you think about leaving this option enabled by default?

Could this behavior be implemented in the future ? Just suggestions, maybe we can create a PR for that.

Thanks!

**Comment by LarsLiden** [comment]
The Action creator UI does default to having "Wait for Response" checked when you create a new action.   We're not quite sure what the use case would be of having a Training Dialog end with a non-terminal action.  (The conversation isn't over at that point.)   Can you explain your use case in more detail?

**Comment by LarsLiden** [comment]
Ah, I see what you are saying.  The issue I see there is that sometimes folks create a bunch of actions at once and we don't want to force them to make the first one terminal.  As an alternative I'm going to add a pop-up message when you try to save the train dialog with a non-terminal action at the end that prevents the save and explains why

**Comment by BelvedereHenrique** [comment]
I see.
That might be the proper solution then, great!

Thanks!

@lucascologni

**Comment by BelvedereHenrique** [comment]
@LarsLiden should we close this one?
Or let it open for reference?
