### ISSUE TITLE
403 Forbidden "Current user is not activated in the system!"

### ISSUE THREAD

**Issue by paramrsingh** [Microsoft/ConversationLearner-Samples#208]
After working through the Quickstart and executing npm run ui, the UI loads with the following error: FETCH_APPLICATIONS_ASYNC Failed
Request failed with status code 403
Forbidden "Current user is not activated in the system!"

Confirmed:
- account is the same used with preview invitation
- my LUIS key is correct and the .env file containing it is present in the directory

**Comment by LarsLiden** [comment]
Project Conversation Learner is currently available by invitation.  During the invitation-only phase, we will prioritize for key customers/partners and internal MS users.  If you would like access to Project Conversation Learner right away, you can [request an invitation](https://i.prefinery.com/projects/hm3oesh4/users/post).

**Comment by paramrsingh** [comment]
@LarsLiden Confirming on my end I received the invitation on 5/22/2018 and got the error above

**Comment by LarsLiden** [comment]
Please confirm that the email address you used to log into LUIS and get your key is the same email to which the invitation email was sent.

**Comment by paramrsingh** [comment]
@LarsLiden Confirmed. Will email you, thanks.

**Comment by KayMKM** [comment]
@paramrsingh I met a same issue. Did you get a solution?

**Comment by paramrsingh** [comment]
@KayMKM Needed to get account enabled. Check link from Lars above, the emails need to match exactly

**Comment by KayMKM** [comment]
@paramrsingh @LarsLiden Thank you. It works now.

**Comment by yearegods** [comment]
Hi I have the same problem @paramrsingh  above.  I am using my personal email with louis.ai and that is the one activated yet the error exists.  @LarsLiden  can you help?

**Comment by LarsLiden** [comment]
Do you happen to be using the EU site for LUIS?  Currently CL is US only so you’d need to use the US LUIS site.

**Comment by tyronelinton** [comment]
Hi @LarsLiden , I am trying to request a invitation to the MS Conversation Learner i have done this but i have not received any email?
