### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by KillerFeature** [Microsoft/ConversationLearner-Samples#219]
I try to install on an Azure VM running Ubuntu server. When I get to the UI I get 
-------
CREATE_APPLICATION_ASYNC Failed
Network Error
Unknown
Is your Bot running?
--------

And Import Tutorials gives me
--------
FETCH_TUTORIAL_ASYNC Failed
Error
Network Error
---------

I have opened port 5050 to get access to the UI. But nothing else. Botservice should be running: 

Creating Conversation Learner Client....
Starting DOL (Direct Offline):
- serviceUrl: http://127.0.0.1:3000
- botUrl: http://127.0.0.1:3978/api/messages
Initialization complete.
BOT Server listening to http://[::]:3978
listening
SDK Service listening to http://[::]:5000

Can you help?

**Comment by mattmazzola** [comment]
I don't understand the scenario.  The UI meant to be communicating with a locally running bot during training.  Once you have trained your model and completed coding your bot you publish it to a cloud such as Azure and in that case the SDK and UI server ports should NOT be exposed.

**Comment by srozga** [comment]
I ran into the same problem on Firefox, but working fine with Chrome. ¯\_(ツ)_/¯

**Comment by LarsLiden** [comment]
We currently only support Chrome (as per documentation)

**Comment by LarsLiden** [comment]
@KillerFeature  - Just to clarify, the UI does not run when the bot is published.   As Matt suggests above, it runs on localhost when you are authoring your bot.  Closing this for now.  Feel free to re-open if you have additional questions.
