### ISSUE TITLE
Cannot Close Help Panel

### ISSUE THREAD

**Issue by seank-com** [Microsoft/ConversationLearner-Samples#227]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

I tried add an API action. I selected the API then pressed the info button for the first argument. From here, I can not close the info panel.

![4pjf2vixxz](https://user-images.githubusercontent.com/1326518/41708958-afbe46ec-754a-11e8-8ca4-7faf25a4f03e.gif)

#### What's the expected behavior?

I expect to be able to close the help tab and get back to work

#### Please tell us about your environment:

macOS High Sierra 10.13.5
node 10.3.0
npm 6.1.0
Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by LarsLiden** [comment]
@seank-com - Thank you for the bug report!  The issue has been fixed and will show up in our next release.
