### ISSUE TITLE
FETCH_BOTINFO_ASYNC while using Firefox 61.0.1

### ISSUE THREAD

**Issue by artus** [Microsoft/ConversationLearner-Samples#258]
#### Do you want to request a _feature_ or report a _bug_?
I want to report a bug

#### What's the current behavior?

While connecting to the UI using Firefox 61.0.1 (or even Edge), I get a network error. Chrome works fine.

I don't get any errors in the consoles where I started the bot and the UI.

![afbeelding](https://user-images.githubusercontent.com/22665347/42865951-8032fc0c-8a6b-11e8-9f38-005e8ca147ed.png)

#### Please tell us about your environment:

Example:
Windows 10 Enterprise Version 1709 OS Build 16299.492
node v8.8.0
npm 5.4.2
Firefox 61.0.1 (64-bit)

**Comment by LarsLiden** [comment]
As per the documentation, while we are in preview we only support Chrome.
