### ISSUE TITLE
Error in Quick Start Step 5

### ISSUE THREAD

**Issue by harry17preet** [microsoft/ConversationLearner-Samples#307]
#### Do you want to request a _feature_ or report a _bug_?
Isuue

#### What's the current behavior?
In the Quick Start guide. Step 5 Open browser to http://localhost:5050,
when navigating to the url , 401 error pops up. I have already got the invitation from Microsoft.

#### What's the expected behavior?
The steps outline is to be executed normally.

**Comment by LarsLiden** [comment]
Are you using the same email that you used to apply for the invitation?  Is it the same email that you used for your LUIS account?

**Comment by ghost** [comment]
.

**Comment by msft-shahins** [comment]
@harry17preet closing this issue. Feel free to comment if you still have problem accessing the service.
