### ISSUE TITLE
I have requested an invitation to the MS Conversation Learner but have not recieved any email

### ISSUE THREAD

**Issue by tyronelinton** [microsoft/ConversationLearner-Samples#355]
Hi @LarsLiden , I have requested an invitation to the MS Conversation Learner but have not recieved any email

**Comment by swadheen** [comment]
Thank you for requesting an invitation to Project Conversation Learner. 

As we continue to scale our service to handle the large number of access requests, we are unable to automatically grant users access to the project. If you have an existing Microsoft relationship, please connect with that team to see if you qualify for an expedited access. Thank you for your understanding!
